services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    networks:
      - kafka-network
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    depends_on:
      - zookeeper
    networks:
      - kafka-network
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  node-app:
    build: .
    container_name: node-app
    depends_on:
      - kafka
    networks:
      - kafka-network
    volumes:
      - .:/app
    working_dir: /app
    command: ["tail", "-f", "/dev/null"] # Keeps the container running

networks:
  kafka-network:
    driver: bridge
