server:
  port: 8081

spring:
  application:
    name: ride-request-service
  datasource:
    url: jdbc:postgresql://postgres-ride-request-service:5432/ride_requests
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true

  kafka:
    bootstrap-servers: broker-1:9092,broker-2:9093,broker-3:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "*"
